export type { MasterSheet, IndentSheet, ReceivedSheet, Sheet, allPermissionKeys, Vendor, UserPermissions, InventorySheet, IssueSheet, StoreInSheet , TallyEntrySheet , PcReportSheet , FullkittingSheet ,PaymentHistory} from "./sheets";
export { type ProductFormValues,type ProductItemProps, type Options,type  FormValues, formSchema } from "./indentForm";
export { type RouteAttributes } from "./routes";
export type PoMasterSheet = {
    timestamp: string;
    party_name: string;
    po_number: string;
    quotation_number: string;
    quotation_date: string;
    enquiry_number: string;
    enquiry_date: string;
    internal_code: string;
    product: string;
    description: string;
    quantity: number;
    unit: string;
    rate: number;
    gst: number;
    discount: number;
    amount: number;
    total_po_amount: number;
    delivery_date: string;
    payment_terms: string;
    number_of_days: number;
    delivery_days: number;
    delivery_type: string;
    term1: string;
    term2: string;
    term3: string;
    term4: string;
    term5: string;
    term6: string;
    term7: string;
    term8: string;
    term9: string;
    term10: string;
    pdf?: string;
    prepared_by?: string;
    approved_by?: string;
    email_send_status?: string;
    firm_name_match?: string;
}